# Sets default memory used for gradle commands. Can be overridden by user or command line properties.
org.gradle.jvmargs=-Xmx1G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true

parchment_minecraft_version=1.21.1
parchment_mappings_version=2024.11.17

# Environment Properties

minecraft_version=1.21.1
minecraft_version_range=[1.21.1, 1.22)
neo_version=21.1.169
neo_version_range=[21.1.0,)
loader_version_range=[4,)

## Mod Properties

mod_id=rightclickandmilk
mod_name=Right Click and Milk
mod_license=MIT License
mod_version=1.0.1
mod_group_id=com.jasbrela.rightclickandmilk
mod_authors=jasbrela
mod_description=A simple addon for Farmer's Delight to make collecting milk a little easier.\nWith an empty glass bottle in hand, right-click a cow to receive a Milk Bottle in return.

## Dependency Properties
farmersdelight_version=6154807
